### ISSUE TITLE
Bot is probably hacked

### ISSUE THREAD

**Issue by pro-coder69** [GDGVIT/Compute-Monitoring-Bot#4] opened 2020-09-11 15:32 UTC
# Bot is probably hacked

This seems like a cool bot, but I just tried to DM it, and I got a weird message. Can you check it out?

## Proof

![image](https://user-images.githubusercontent.com/71141691/92944634-de859680-f471-11ea-9dd0-eeac843103c0.png)

P.S. I think your bot token is in the first commit in the repository. Thanks for your help :smile:

**Comment by abhishekkushwaha4u** [comment] 2020-09-11 18:31
Thank you for bringing it to our notice. We changed our bot token multiple times but still, the issue is not resolved as of now. We'd request you to report any holes in the security you see in this repo.

**Comment by raysandeep** [comment] 2020-09-11 19:11
Hey, Thanks for reporting the bug. 
We are trying the debug the issue and working on a fix for the same!

**Comment by searchformyusername** [comment] 2020-09-11 20:10
@pro-coder69 can u try once again please, it will make a good ctf by the way

**Comment by Geek-ubaid** [comment] 2020-10-04 10:59
Issue resolved in he last PR. Closing it now.

**Closed as completed** 2020-10-04 11:00 UTC
Labels: bug
